language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install: pip install 'PyYAML' 'python-dateutil' 'pytest >=3.6.0' 'distutils-pytest' 'pytest-dependency >=0.2'
script: make test

# Local Variables:
# mode: yaml
# End:
